### ISSUE TITLE
song not playing

### ISSUE THREAD

**Issue by kabirsingh2004** [oceanroleplay/discord-music-bot#1]
/home/runner/discord-music-bot/node_modules/@discordx/music/build/classes/Queue.js:222
                error.resource.metadata,
                               ^

TypeError: Cannot read properties of undefined (reading 'metadata')
    at MyQueue.processQueue (/home/runner/discord-music-bot/node_modules/@discordx/music/build/classes/Queue.js:222:32)

how to fix this ?

**Comment by oceanroleplay** [comment]
@kabirsingh2004 can you provide a reproducible code example?

**Comment by kabirsingh2004** [comment]
> @kabirsingh2004 can you provide a reproducible code example?

i use your example bot please check

**Comment by oceanroleplay** [comment]
maybe that is because of outdated dependencies, I have now updated them. So try now. If issue persist, open another issue.
