### ISSUE TITLE
Deploying Music Bot 410 Issue

### ISSUE THREAD

**Issue by Azshurith** [oceanroleplay/discord-music-bot#2]
When testing the bot from my local server, it works pretty fine. But after deploying it to Heroku, I keep on getting Error 410.
Even if I keep on redeploying my application, Error 410 will return an hour after the bot plays music from a discord channel.

**Comment by oceanroleplay** [comment]
Error 410 is from `ytdl`, please add a `FFMPEG` buildpack, if you are deploying on heroku, and try redeploy.

**Comment by oceanroleplay** [comment]
Join our [discord server](https://discord.gg/yHQY9fexH9) for more close discussion on this
