### ISSUE TITLE
Cannot enter my Token

### ISSUE THREAD

**Issue by RomzillaKhan** [oceanroleplay/discord-music-bot#5]
The title says it all, i follow all the steps. still can't run the bot.
I got this message:

F:\serveur discord\discord-music-bot-main\node_modules\discord.js\src\client\Client.js:237
    if (!token || typeof token !== 'string') throw new Error('TOKEN_INVALID');
                                                   ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (F:\serveur discord\discord-music-bot-main\node_modules\discord.js\src\client\Client.js:237:52)
    at Client.login (F:\serveur discord\discord-music-bot-main\node_modules\discordx\build\cjs\Client.js:194:22) {
  [Symbol(code)]: 'TOKEN_INVALID'
}

I tried to enter the command with and without "<>" with both spaces and not.
I also tried to generate another token.

It wont recognize my Token.

**Comment by oceanroleplay** [comment]
manually pass the token at https://github.com/oceanroleplay/discord-music-bot/blob/main/src/client.ts#L37

see how env works in nodejs at https://nodejs.dev/learn/how-to-read-environment-variables-from-nodejs

**Comment by RomzillaKhan** [comment]
Thanks a lot :D 
Also the loop button doesn't seem to work.
besides this, the bot is amazing, thank you :D
